a = input('Digite algo:')
print('O tipo digitado é {}'.format(type(a)))
print('Só tem espaço? {}'.format(a.isspace()))
print('È numerico? {}'.format(a.isnumeric()))
print('É alfabetico? {}'.format(a.isalpha()))
print('É alphanumerico? {}'.format(a.isalnum()))
print('Esta em maiscula? {}'.format(a.isupper()))
print('Está em minuscula? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))
